name: Scheduled Running 

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 8 am HK time (midnight UTC)
  workflow_dispatch:  # Manual run trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install make
        run: sudo apt-get install make

      - name: Install project dependencies
        run: make install

      - name: Export DB_PW secret
        run: echo "$DB_PW" > service_account.json

      - name: Run Python application
        run: python crawler.py
        env:
          DB_PW: ${{ secrets.DB_PW }}

      - name: Git Commit and Push
        run: |
          git config --local user.email "johnku2011@github.com"
          git config --local user.name "John Ku"
          git add .
          git commit -m "Automatic commit from GitHub Actions"
          git push
